#!/usr/bin/env python3

import sys
import subprocess
from typing import (
    List,
)

SCANNER_COMMANDS: List[str] = ["rl-scan", "rl-prune"]


def usage() -> None:
    print("Error: Invalid scanner command specified")
    print("\nValid commands are:")
    for cmd in SCANNER_COMMANDS:
        print(f"\t{cmd}")
    sys.exit(1)


if len(sys.argv) < 2:
    usage()

if sys.argv[1] not in SCANNER_COMMANDS:
    usage()

sys.exit(
    subprocess.run(
        sys.argv[1:],
        shell=False,
        check=False,
    ).returncode,
)
