#!/usr/bin/env python3

import os
import sys
from typing import NoReturn

from constants import (
    EXIT_FATAL,
    SCANNER_COMMANDS,
)


def usage() -> NoReturn:
    print("Error: Invalid scanner command specified", file=sys.stderr)
    print("\nValid commands are:", file=sys.stderr)
    for cmd in SCANNER_COMMANDS:
        print(f"\t{cmd}", file=sys.stderr)
    sys.exit(EXIT_FATAL)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        usage()

    if sys.argv[1] not in SCANNER_COMMANDS:
        usage()

    try:
        os.execvp(sys.argv[1], sys.argv[1:])  # noqa: S606
    except Exception as e:
        print(f"Error: {sys.argv[1]}; {str(e)}", file=sys.stderr)
        sys.exit(EXIT_FATAL)
