#!/usr/bin/env python3

import sys
import subprocess
from typing import (
    List,
)

from constants import (
    SCANNER_COMMANDS,
    EXIT_FATAL,
)


def usage() -> None:
    print("Error: Invalid scanner command specified")
    print("\nValid commands are:")
    for cmd in SCANNER_COMMANDS:
        print(f"\t{cmd}")
    sys.exit(EXIT_FATAL)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        usage()

    if sys.argv[1] not in SCANNER_COMMANDS:
        usage()

    try:
        rr = subprocess.run(
            sys.argv[1:],
            shell=False,
            check=False,
        ).returncode
        sys.exit(rr)

    except Exception as e:
        print(f"Error: {sys.argv[1:]}; {str(e)}")
        sys.exit(EXIT_FATAL)
