#!/usr/bin/env python3


import argparse
import sys

from cimessages import Messages
from constants import EXIT_FATAL
from myargs import (
    my_common_epilog,
    my_common_prog_description,
    params_basic,
    params_import_url,
)
from rlsecure import (
    collect_password_info,
    do_init_scanurl_report_status,
)
from validators import (
    validate_import_url,
    validate_purl_repro_store,
    validate_report_path_exists_and_empty,
    validate_store_diff_purl,
    validate_store_level_purl,
)


def _my_params() -> argparse.Namespace:
    prog: str = "rl-scan-url"

    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        prog=prog,
        description=my_common_prog_description(prog=prog),
        epilog=my_common_epilog(),
    )

    params_basic(
        parser=parser,
    )

    params_import_url(
        parser=parser,
    )

    params = parser.parse_args()

    validate_store_level_purl(params=params)
    validate_store_diff_purl(params=params)
    validate_purl_repro_store(params=params)
    validate_report_path_exists_and_empty(params=params)
    validate_import_url(params=params)

    if params.purl is None:
        params.purl = "project/package@target"

    return params


def main() -> int:
    params = _my_params()
    reporter = Messages.create(params.message_reporter)
    passwords, vault_key = collect_password_info(params)

    return do_init_scanurl_report_status(
        params=params,
        reporter=reporter,
        passwords=passwords,
        vault_key=vault_key,
    )


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print(f"Error: {str(e)}", file=sys.stderr)
        sys.exit(EXIT_FATAL)
